apiVersion: apps/v1
kind: Deployment
metadata:
  name: $k8s_service_name
  labels:
    app: $k8s_service_name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $k8s_service_name
  template:
    metadata:
      labels:
        app: $k8s_service_name
    spec:
      containers:
        - name: $k8s_service_name
          image: $k8s_image
          ports:
            - containerPort: $k8s_port
          
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernates

          livenessProbe:
            httpGet:
              path: '/sanityCheck'
              port: $k8s_port
            initialDelaySeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            periodSeconds: 10
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: '/sanityCheck'
              port: $k8s_port
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10