version: "3.8"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://host.docker.internal:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  music-streaming-user:
    image: sinsung6722/music-streaming-user:v1
    depends_on:
      - kafka
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  music-streaming-music:
    image: sinsung6722/music-streaming-music:v1
    depends_on:
      - kafka
    ports:
      - "8083:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  music-streaming-file:
    image: sinsung6722/music-streaming-file:v1
    depends_on:
      - kafka
    ports:
      - "8084:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  music-streaming-play-list:
    image: sinsung6722/music-streaming-play-list:v1
    depends_on:
      - kafka
    ports:
      - "8085:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  music-streaming-comment:
    image: sinsung6722/music-streaming-comment:v1
    depends_on:
      - kafka
    ports:
      - "8086:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker


  music-streaming-collected-data:
    image: sinsung6722/music-streaming-collected-data:v1
    depends_on:
      - kafka
    ports:
      - "8087:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  music-streaming-gateway:
    image: sinsung6722/music-streaming-gateway:v1
    ports:
      - "8088:8088"
    environment:
      SPRING_PROFILES_ACTIVE: docker
