apiVersion: apps/v1
kind: Deployment
metadata:
  name: $k8s_service_name
  labels:
    app: $k8s_service_name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $k8s_service_name
  template:
    metadata:
      labels:
        app: $k8s_service_name
    spec:
      containers:
        - name: $k8s_service_name
          image: $k8s_image
          ports:
            - containerPort: $k8s_port